version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sigs.k8s.io/kustomize/kyaml
    versions:
    - 0.10.10
    - 0.10.11
    - 0.10.13
    - 0.10.14
    - 0.10.15
    - 0.10.16
    - 0.10.6
    - 0.10.7
    - 0.10.8
    - 0.10.9
  - dependency-name: github.com/google/go-cmp
    versions:
    - 0.5.4
    - 0.5.5
  - dependency-name: github.com/jenkins-x/jx-api/v4
    versions:
    - 4.0.27
    - 4.0.28
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.14.2
    - 1.15.0
    - 1.15.1
    - 1.15.2
    - 1.16.0
  - dependency-name: github.com/jenkins-x/go-scm
    versions:
    - 1.5.218
    - 1.5.221
    - 1.5.223
    - 1.5.224
    - 1.5.225
    - 1.5.229
    - 1.6.1
    - 1.6.13
    - 1.6.3
    - 1.6.4
    - 1.6.5
    - 1.6.6
    - 1.6.7
    - 1.6.9
  - dependency-name: github.com/sethvargo/go-envconfig
    versions:
    - 0.3.4
  - dependency-name: k8s.io/api
    versions:
    - 0.20.5
  - dependency-name: k8s.io/apimachinery
    versions:
    - 0.20.5
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.8.0
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.1
    - 1.1.2
  - dependency-name: k8s.io/helm
    versions:
    - 2.17.0+incompatible
  - dependency-name: github.com/onsi/gomega
    versions:
    - 1.10.4
    - 1.10.5
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.7.0
  - dependency-name: github.com/fatih/color
    versions:
    - 1.10.0
  - dependency-name: github.com/google/uuid
    versions:
    - 1.2.0
  - dependency-name: gopkg.in/yaml.v2
    versions:
    - 2.4.0
